[build]
base = "my-react-app"
command = "npm ci --include=dev && npm run build"
publish = "dist"

[build.environment]
NPM_FLAGS = "--include=dev"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200